//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizinAja_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantAnswer
    {
        public int ID { get; set; }
        public int ParticipantID { get; set; }
        public int QuestionID { get; set; }
        public string Answer { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Question Question { get; set; }
    }
}
